on: push
name: npm build, lint, test and publish
jobs:
  build-and-publish:
    name: build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: npm install
        uses: actions/setup-node@v1
        with:
          args: install
      - name: npm test
        uses: actions/setup-node@v1
        with:
          args: run test
      - name: npm lint
        uses: actions/setup-node@v1
        with:
          args: run lint
      - name: Tag the Docker image
        run: docker build -t irt01/node-web-app:new .
      - name: docker login
        uses: actions-hub/docker/login@master
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      - name: docker push
        uses: actions/checkout@v2
        with:
          args: irt01/node-web-app:new .
